Update spawn and remove plugins
MOV-AI/movai_ign_plugins pull request #67
Opened 2023-04-26 17:30 UTC by bernardomovai

Update spawn and removal plugins. Both plugins now receive a string with the names of the models to spawn/remove.
Relates to
 [https://movai.atlassian.net/browse/RP-1727](url) 
and
[https://movai.atlassian.net/browse/RP-1728](url)

- [x] Make sure you are opening from a **topic/feature/bugfix branch**
- [x] Ensure that the PR title represents the desired changes
- [x] Ensure that the PR description detail the desired changes
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-05-02 10:23 UTC, filipa-movai commented on spawn_model/SpawnModel.cc
>    std::string topic = "/world/" + worldName + "/create";
these are not very good variable names

2023-05-02 10:24 UTC, filipa-movai approved these changes

2023-05-02 10:24 UTC, filipa-movai commented
Looks good to me but would like to get @jmspribeiro opinion since it is more his area of expertise

2023-05-02 10:50 UTC, jmspribeiro commented on spawn_model/SpawnModel.cc
> +        std::string reqStr = std::string("<sdf version='1.7'>") +
Consider using a xml library for writing xml content (tinyxml is a good one)

2023-05-02 10:51 UTC, jmspribeiro approved these changes
LGTM

2023-05-02 10:58 UTC, jmspribeiro requested changes
please bump the version

2023-05-08 13:16 UTC, jmspribeiro approved these changes

2023-05-08 14:02 UTC, merged